=== AlanTeeWeiLoon/E-Commerce-Applications-with-XML-ASP.NET/DECXML Assignment/DECXML Assignment/xml/Feedbacks.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!-- Feedback* indicate that element can appear many times-->
<!ELEMENT Feedbacks (Feedback*)>
<!--Defining Feedback's child element sequence-->
<!ELEMENT Feedback (feedback_id,name,email,subject,message,date)>
<!ELEMENT feedback_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== AlanTeeWeiLoon/E-Commerce-Applications-with-XML-ASP.NET/DECXML Assignment/DECXML Assignment/xml/Feedbacks.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Feedbacks SYSTEM "Feedbacks.dtd"[]>
<Feedbacks>
  <Feedback>
    <feedback_id>Feedback1</feedback_id>
    <name>Alan</name>
    <email>alan@gmail.com</email>
    <subject>Good</subject>
    <message>Good Platform</message>
    <date>11/30/2021</date>
  </Feedback>
  <Feedback>
    <feedback_id>Feedback2</feedback_id>
    <name>Kelvin</name>
    <email>kelvin@gmail.com</email>
    <subject>Feedback for DECXML</subject>
    <message>Good online shopping experience!</message>
    <date>12/5/2021</date>
  </Feedback>
  <Feedback>
    <feedback_id>Feedback3</feedback_id>
    <name>Ben</name>
    <email>ben@gmail.com</email>
    <subject>Feedback from Ben</subject>
    <message>Price reasonable and product nice</message>
    <date>12/5/2021</date>
  </Feedback>
  <Feedback>
    <feedback_id>Feedback4</feedback_id>
    <name>test1</name>
    <email>test@gmail.com</email>
    <subject>Feedback1</subject>
    <message>Good Product</message>
    <date>12/8/2021</date>
  </Feedback>
</Feedbacks>
