=== AlanTeeWeiLoon/E-Commerce-Applications-with-XML-ASP.NET/DECXML Assignment/DECXML Assignment/xml/Users.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!--User element contain single element called User-->
<!-- User* indicate that element can appear many times-->
<!ELEMENT Users (User*)>
<!--Defining User's child element sequence-->
<!ELEMENT User (name,age,address,password,position)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!--Defining username attribute must contain character data-->
<!ATTLIST User email CDATA #REQUIRED>

=== AlanTeeWeiLoon/E-Commerce-Applications-with-XML-ASP.NET/DECXML Assignment/DECXML Assignment/xml/Users.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Users SYSTEM "Users.dtd"[]>
<Users>
  <User email="admin@gmail.com">
    <name>Admin</name>
    <age>0</age>
    <address>None</address>
    <password>admin</password>
    <position>Admin</position>
  </User>
  <User email="alan@gmail.com">
    <name>Alan</name>
    <age>21</age>
    <address>Parkhill Residence</address>
    <password>123456</password>
    <position>User</position>
  </User>
  <User email="caemas@gmail.com">
    <name>Caemas</name>
    <age>21</age>
    <address>Parkhill Residence C Block</address>
    <password>123456</password>
    <position>User</position>
  </User>
  <User email="ben@gmail.com">
    <name>Ben</name>
    <age>21</age>
    <address>Parkhill Residence Block D</address>
    <password>123456</password>
    <position>User</position>
  </User>
  <User email="test1@gmail.com">
    <name>Test1</name>
    <age>21</age>
    <address>apu</address>
    <password>123456</password>
    <position>User</position>
  </User>
</Users>
